version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "javax"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "jpa"
    schedule:
      interval: "daily"
